name: 'Build & auto-publish to PyPI'
author: 'Conchylicultor'
description: 'Build & publish to PyPI when `my_module.__version__` is increased'
branding:
  icon: upload-cloud
  color: orange

inputs:
  pkg-name:
    description: 'Name of the PyPI package (optional).'
    required: false
  pypi-token:
    description: 'Token of the PyPI account publishing the project.'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    # Setup Python
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
  
    - run: pip install -e .
      shell: bash
  
    - run: pip install packaging
      shell: bash

    # Get the local and PyPI versions
    # Check if local `__version__` < pip version
    # Output: `compare-version.outputs.should-release`
    - id: compare-version
      run: |
        python ${{github.action_path}}/src/compare_version.py \
          --pkg_name="${{ inputs.pkg-name }}"
      shell: bash

    - run: |
        echo \
          version=${{ steps.compare-version.outputs.version }} \
          should-release=${{ steps.compare-version.outputs.should-release }}
      shell: bash

    # Publish the package (if local `__version__` < pip version)
    - if: steps.compare-version.outputs.should-release == 'true'
      uses: etils-actions/pypi-build-publish@v1
      with:
        pypi-token: ${{ inputs.pypi-token }}
