name: 'Build & auto-publish to PyPI'
author: 'Conchylicultor'
description: 'Build & publish to PyPI when `my_module.__version__` is increased'
branding:
  icon: upload-cloud
  color: orange

inputs:
  module-name:
    description: 'The name of the module to import.'
    required: true
  pypi-token:
    description: 'Token of the PyPI account publishing the project.'
    required: true

runs:
  using: "composite"
  steps:
    - run: pip install packaging
      shell: bash

    # Extract current local `__version__`
    # Output: `local-version.outputs.version`
    - id: local-version
      run: |
        VERSION=$(python -c "import {{ inputs.module-name }} ; print({{ inputs.module-name }}.__version__)")
        echo ::set-output name=version::${VERSION}
      shell: bash

    # Extract current `pip version`
    # Output: `pip-version.outputs.version`
    - id: pip-version
      run: python src/get_pypi_version.py {{ inputs.module-name }} --github_action_output_name=version
      shell: bash

    # Check if local `__version__` < pip version
    # Output: `compare-version.outputs.should-release`
    - id: compare-version
      run: |
        python src/compare_version.py \
          --local_version=${{ steps.local-version.outputs.version }} \
          --pypi_version=${{ steps.pip-version.outputs.version }}
      shell: bash

    # Publish the package (if local `__version__` < pip version)
    - if: steps.compare-version.outputs.should-release == 'true'
      uses: etils-actions/pypi-build-publish@v1
      with:
        pypi-token: ${{ inputs.pypi-token }}
